//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public Type()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int id { get; set; }
        public string type1 { get; set; }
        public string address { get; set; }
        public string price { get; set; }
        public string qty { get; set; }
    
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
